### PR TITLE
Fix leak period detection

### PR DESCRIPTION
**Pull request by Lauri-Nomme**
getData() method not available on response, replace with data.
Fetch leak period setting for analyzed project instead of globally.
Tolerate missing value for sonar.leak.period

### CODE REVIEW

**Comment by Lauri-Nomme** [comment]
Hi @ptrovatelli could you take a look?

**Comment by ptrovatelli** [comment]
hello @Lauri-Nomme 

Sorry for the late reply. 

The period can be configured at different levels: see https://docs.sonarqube.org/8.0/project-administration/new-code-period/
`You can set a New Code Period at the global, project, or branch level.`

Shouldn't we leave the option to use the global parameter? (should be the default for backward compatibility). 
Maybe: 
- `--sinceleakperiod=true` : use the global parameter
- `--sincecomponentleakperiod=true` : use the parameter at component level

Also, can you tell me what environment you used for testing this (sonarcloud, sonarqube community, other? version)? I have tried on the current sonarcloud (sonarqube 8.0.0.26660) and the `sinceLeakPeriod` seems to be ignored. See for example 
`
curl https://sonarcloud.io/api/issues/search?componentKeys=tomcat_180410&ps=500&p=1&statuses=OPEN,CONFIRMED,REOPENED&resolutions=&s=STATUS&asc=no&sinceLeakPeriod=true&types=VULNERABILITY&organization=java_1804
`

returns the same number of vuln than without the sinceLeakPeriod parameter , 239
we can see here that many of them are older than 30 days, which is the configured period on the component: https://sonarcloud.io/project/issues?id=tomcat_180410&resolved=false&severities=MINOR&types=VULNERABILITY

`
curl "https://sonarcloud.io/api/settings/values?keys=sonar.leak.period"
{"settings":[]}
`

`
$ curl "https://sonarcloud.io/api/settings/values?component=tomcat_180410&keys=sonar.leak.period"
{"settings":[{"key":"sonar.leak.period","value":"30"}]}
`

I've just set up a new environment with sonarqube community 8. I need to wait for a couple of days for issues to get old :)

**Comment by Lauri-Nomme** [comment]
Using this on `Community EditionVersion 8.9.7 (build 52159)`.
Agreed on retaining prev behavior via introducing new cmd like arg.

**Comment by Lauri-Nomme** [comment]
Looked into this.

The data flow is such that the modification i did only applies to the leak period displayed in the report.
There is no way to specify which leak period to use for the analysis, just whether to use sinceLeakPeriod=true or not.
Sonar itself then applies the leak period configured on the innermost level.

**Comment by Lauri-Nomme** [comment]
Reading the source a bit more and experimenting with the built-in h2 database, it appears the `component` parameter of `settings/values` endpoint actually accepts various values, like project keys but also individual file names inside projects, like `org.example:jdbcpgcopytest:src/main/java/FieldBinaryExporter.java`.
It supports everything that is stored in the `components` table in `kee` column.

I have no access to a developer/enterprise sonar instance (which support branches) to verify, whether the project branches also appear in that table, but if they do, we could simply append `:$branch` to the `$sonarComponent` supplied and get the effective leak period that way.

`components` table contents w/ a test project analyzed:
```
sql> select kee from components;
KEE
org.example:jdbcpgcopytest
org.example:jdbcpgcopytest:src/main/java
org.example:jdbcpgcopytest:src/main/java/BatchedInsert.java
org.example:jdbcpgcopytest:src/main/java/Buf.java
org.example:jdbcpgcopytest:src/main/java/CopyInsert.java
org.example:jdbcpgcopytest:src/main/java/FieldBinaryExporter.java
org.example:jdbcpgcopytest:src/main/java/Fixture.java
org.example:jdbcpgcopytest:src/main/java/Holder.java
org.example:jdbcpgcopytest:src/main/java/JDBCPgCopyTest.java
org.example:jdbcpgcopytest:src/main/java/SliceStat.java
org.example:jdbcpgcopytest:src/main/java/TestBase.java
org.example:jdbcpgcopytest:src/main/java/XTimestamp.java
```

Example API requests:
```
$ curl -u ${SQ_KEY}: "http://localhost:9000/api/settings/values?component=org.example:jdbcpgcopytest&keys=sonar.leak.period"

{"settings":[{"key":"sonar.leak.period","value":"asd"}]}
```

```
$ curl  -u ${SQ_KEY}: "http://localhost:9000/api/settings/values?component=org.example:jdbcpgcopytest:src/main/java&keys=sonar.leak.period"
{"settings":[{"key":"sonar.leak.period","value":"asd","inherited":true}]}
```

**Comment by Lauri-Nomme** [comment]
Indeed, this `sonar.leak.period` setting is not reliable.
Testing on a `Developer EditionVersion 8.9.7` reveals it's not returned even if configured; neither on the component- or branch level.

However, the leak period for the last analysis can be retrieved from:
```
$ curl -s -u $SQ_KEY "http://10.222.1.1:9000/api/qualitygates/project_status?projectKey=org.example:jdbcpgcopytest&branch=tere" | jq .projectStatus.period
{
  "mode": "NUMBER_OF_DAYS",
  "date": "2022-02-28T21:53:27+0000",
  "parameter": "3"
}
```

```
curl -s -u $SQ_KEY "http://10.222.1.1:9000/api/qualitygates/project_status?projectKey=org.example:jdbcpgcopytest" | jq .projectStatus.period
{
  "mode": "NUMBER_OF_DAYS",
  "date": "2022-02-28T21:50:06+0000",
  "parameter": "11"
}
```

So, this PR can be ignored and i'll implement this on top of the https://github.com/soprasteria/sonar-report/pull/87

**Pull request closed without merging**
